### ISSUE TITLE
Better Biomes Crash

### ISSUE THREAD

**Issue by 23KiaraMinecraft** [CrypticVerse/BetterBiomes-Forge#2]
I am playing on the latest version of Forge: (Forge - 51.0.8)

Crash Report: (https://pastebin.com/BAbNkgUK)
Latest Log: (https://pastebin.com/zCPfHySy)

**Comment by CrypticVerse** [comment]
@23KiaraMinecraft Fixed in BetterBiomes-Forge 3.0.0.0-patch.1
